title: Lanhang Ye
position: Doctor of Engineering
affiliation: Nagoya University
email: ye.lanhang.n2[at]f.mail.nagoya-u.ac.jp
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=3kXV9zcAAAAJ&hl=en
github_link: https://github.com/LanhangYe
linkedin: https://www.linkedin.com/in/lanhang-ye-08b88482/
avatar: ./assets/img/self-pic.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Update Jan. 2024.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
